### ISSUE TITLE
Convert .proj files to Makefiles

### ISSUE THREAD

**Issue by scottmc** [HaikuArchives/TransPlus#2]
Use paladin to import the .proj files and then export then to Makefiles.

**Comment by kaesaecracker** [comment]
Should I still do this or are my makefiles okay?

**Comment by scottmc** [comment]
you can try it and compare the two to see if anything gets missed.  I think paladin might be exporting at makefile 2.3 though, so your's is probably better.  I opened the ticket before seeing you had already made makefiles.
